DROP TABLE CITY_DETAILS;
CREATE TABLE CITY_DETAILS(CITY VARCHAR2(50) NOT NULL, POPULATION NUMBER, LATITUDE NUMBER, LONGITUDE NUMBER, PRIMARY KEY(CITY));
INSERT INTO CITY_DETAILS (CITY, POPULATION, LATITUDE, LONGITUDE) VALUES ('Aalborg', 163231, 57.2, 9.55);
INSERT INTO CITY_DETAILS (CITY, POPULATION, LATITUDE, LONGITUDE) VALUES ('Aarhus', 336411, 56.8, 10.13);
INSERT INTO CITY_DETAILS (CITY, POPULATION, LATITUDE, LONGITUDE) VALUES ('Odense', 185206, 55.23, 10.23);
INSERT INTO CITY_DETAILS (CITY, POPULATION, LATITUDE, LONGITUDE) VALUES ('Roskilde', 50393, 55.38, 12.5);